### ISSUE TITLE
Move UI recipes out from blueprints

### ISSUE THREAD

**Issue by soofstad** [equinor/data-modelling-storage-service#279] opened 2022-11-23 09:21 UTC
Sub issues:

- [x] #282
- [ ] dm-cli create & refresh lookup tables
- [ ] something with api to fetch/append recipes to "fetchBlueprint"

Suggestion:

-  A uiRecipe lookup entity for each app

```json
"type": "AppSettings",

"uiRecipePackage":  ["DMSS://data_soruce/recipesPakcage", "DMSS://data_soruce/anotherPackage"],



```

Each recipe package will have UiRecipeLinks as content. Subfolders should also be parsed
```json

[
{
"type": "RecipeLink",
"blueprintType": "myType",
"recipes": [
   {
    "type": "UiRecipe",
   "_id:" "12315-3464356-23464356"
   },
   {
    "type": "UiRecipe",
   "plugin:" "signal-plot"
   }
  ]}
]
```

UiREcipeLookupTable will be created in DMSS-internal (memory cached) upon import (created on client).

LookupTable:

```json
{
 "application1": {
      "uiRecipes": { 
        "myBlueprintType": [
              {
                 "type": "uiRecipe",
                 "plugin": "signal-plot"
              }
          ],
     "__default": []

},
      "storageRecipes": { }
   }
 "dmss": {
  "uiRecipes": {
   "system/SIMOS/Blueprint": {}
   "__default__" :  []
}

}


}

```

**Comment by eoaksnes** [comment] 2022-11-30 17:40
duplicate of https://github.com/orgs/equinor/projects/189/views/3

**Closed by eoaksnes** 2022-11-30 17:40 UTC
